services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase

    networks:
      - backend

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5444:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

  testdb:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5445:5432"
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data: